version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/product-store-api
      - JWT_SECRET=secret_key
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:




